In [110]:
# Importación de la librería Numpy
import numpy
# Creación de un arreglo
arreglo = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arreglo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
import numpy as np
arreglo = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arreglo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
# Importación de la librería Pandas
import pandas as pd
# Creación de un Dataframe
df = pd.DataFrame(arreglo)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [113]:
# Modificación de las columnas del Data Frame
df = pd.DataFrame(data = arreglo, index = ['A', 'B', 'C'], columns = ['D', 'E', 'F'])
df

   D  E  F
A  1  2  3
B  4  5  6
C  7  8  9

In [114]:
# Sección superior (ENCABEZADO)
df.head(2)

   D  E  F
A  1  2  3
B  4  5  6

In [115]:
# Información de cada columna
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       3 non-null      int64
 1   E       3 non-null      int64
 2   F       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [116]:
# Dimensión del DataFrame
df.shape

(3, 3)

In [117]:
# Cálculo de estadísticas generales de la tabla
df.describe()

         D    E    F
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [118]:
# Nombres de las columnas
df.columns

Index(['D', 'E', 'F'], dtype='object')

In [119]:
# Nombres de las filas
df.index

Index(['A', 'B', 'C'], dtype='object')

In [120]:
# Adición de una nueva fila al DF
df.loc['G'] = [11, 12, 13]
df

    D   E   F
A   1   2   3
B   4   5   6
C   7   8   9
G  11  12  13

In [121]:
# Adición de una nueva columna al DF
df['H'] = [17, 16, 15, 14]
df

    D   E   F   H
A   1   2   3  17
B   4   5   6  16
C   7   8   9  15
G  11  12  13  14

In [122]:
# Extracción de columnas de un DF
df2 = df[['E', 'H']]
df2

    E   H
A   2  17
B   5  16
C   8  15
G  12  14

In [123]:
# Extracción de filas de un DF
df3 = df.iloc[0:2]   # Extrae las primeras dos filas
df3

   D  E  F   H
A  1  2  3  17
B  4  5  6  16

In [124]:
# Cambio de nombre de TODAS las columnas
df.columns = ['Columna1', 'Columna2', 'Columna3', 'Columna4']
df

   Columna1  Columna2  Columna3  Columna4
A         1         2         3        17
B         4         5         6        16
C         7         8         9        15
G        11        12        13        14

In [125]:
# Cambio de nombre en ALGUNAS columnas
df.rename(columns = {'Columna1' : 'C1', 'Columna2' : 'C2'}, inplace = True)
df

   C1  C2  Columna3  Columna4
A   1   2         3        17
B   4   5         6        16
C   7   8         9        15
G  11  12        13        14

In [126]:
# Cambio de nombre en ALGUNAS filas
df.rename(index = {'A' : 'Dato1', 'B' : 'Dato2'}, inplace = True)
df

       C1  C2  Columna3  Columna4
Dato1   1   2         3        17
Dato2   4   5         6        16
C       7   8         9        15
G      11  12        13        14

In [127]:
# Ordenamiento de DF
df4 = df.sort_values('Columna4', ascending = True)
df4

       C1  C2  Columna3  Columna4
G      11  12        13        14
C       7   8         9        15
Dato2   4   5         6        16
Dato1   1   2         3        17

In [147]:
# Verificación de condiciones en DF
df['C2'] > 5

Dato1    False
Dato2    False
C         True
G         True
Name: C2, dtype: bool

In [149]:
df[df['C2'] > 5]

   C1  C2  Columna3  Columna4
C   7   8         9        15
G  11  12        13        14

In [151]:
# Verificar múltiples condiciones

condicion1 = df['C1'] > 1
condicion2 = df['C2'] < 12
df[condicion1 & condicion2]

       C1  C2  Columna3  Columna4
Dato2   4   5         6        16
C       7   8         9        15

In [153]:
# Ejercicio: Crear DF de mascotas de las diapositivas
arreglo = np.array([['Bella', 'Labrador', 'Café', 56, 24, '2013-07-01'],
                    ['Charlie', 'Poodle', 'Negro', 43, 24, '2016-09-16'],
                    ['Lucy', 'Chow Chow', 'Café', 46, 24, '2014-08-25'],
                    ['Cooper', 'Schnauzer', 'Gris', 49, 17, '2011-12-11'],
                    ['Bernie', 'San Bernardo', 'Blanco', 77, 74, '2018-02-27']])
arreglo

array([['Bella', 'Labrador', 'Café', '56', '24', '2013-07-01'],
       ['Charlie', 'Poodle', 'Negro', '43', '24', '2016-09-16'],
       ['Lucy', 'Chow Chow', 'Café', '46', '24', '2014-08-25'],
       ['Cooper', 'Schnauzer', 'Gris', '49', '17', '2011-12-11'],
       ['Bernie', 'San Bernardo', 'Blanco', '77', '74', '2018-02-27']],
      dtype='<U21')

In [155]:
df = pd.DataFrame(data = arreglo, columns = ['Nombre', 'Raza', 'Color', 'Altura_cm', 'Peso_kg', 'Fecha_Nac'])
df

    Nombre          Raza   Color Altura_cm Peso_kg   Fecha_Nac
0    Bella      Labrador    Café        56      24  2013-07-01
1  Charlie        Poodle   Negro        43      24  2016-09-16
2     Lucy     Chow Chow    Café        46      24  2014-08-25
3   Cooper     Schnauzer    Gris        49      17  2011-12-11
4   Bernie  San Bernardo  Blanco        77      74  2018-02-27

In [159]:
# 1) Extraiga aquellos registros de los perros cuya fecha de nacimiento es anterior al 1 de Enero del 2015.
df2 = df[df['Fecha_Nac'] < '2015-01-01']
df2

   Nombre       Raza Color Altura_cm Peso_kg   Fecha_Nac
0   Bella   Labrador  Café        56      24  2013-07-01
2    Lucy  Chow Chow  Café        46      24  2014-08-25
3  Cooper  Schnauzer  Gris        49      17  2011-12-11

In [163]:
# 2) Extraiga aquellos registros de los perros cuya estatura es mayor a 50 cms.
df['Altura_cm'] = df['Altura_cm'].astype(int)

df3 = df[df['Altura_cm'] > 50]
df3

   Nombre          Raza   Color  Altura_cm Peso_kg   Fecha_Nac
0   Bella      Labrador    Café         56      24  2013-07-01
4  Bernie  San Bernardo  Blanco         77      74  2018-02-27

In [165]:
# Agregue una nueva columna a este Dataframe que calcule el índice de masa muscular (IMM) para cada perro, el cual está dado por la fórmula:
# IMM = (Peso en kg) / (Altura en mts)^2
df['Peso_kg'] = df['Peso_kg'].astype(int)

df['IMM'] = df['Peso_kg'] / (df['Altura_cm'] / 100) ** 2
df

    Nombre          Raza   Color  Altura_cm  Peso_kg   Fecha_Nac         IMM
0    Bella      Labrador    Café         56       24  2013-07-01   76.530612
1  Charlie        Poodle   Negro         43       24  2016-09-16  129.799892
2     Lucy     Chow Chow    Café         46       24  2014-08-25  113.421550
3   Cooper     Schnauzer    Gris         49       17  2011-12-11   70.803832
4   Bernie  San Bernardo  Blanco         77       74  2018-02-27  124.810255

In [169]:
# Otras manipulaciones
df2 = df[['Nombre', 'Raza', 'IMM']]
df2

    Nombre          Raza         IMM
0    Bella      Labrador   76.530612
1  Charlie        Poodle  129.799892
2     Lucy     Chow Chow  113.421550
3   Cooper     Schnauzer   70.803832
4   Bernie  San Bernardo  124.810255

In [171]:
df2 = df2.sort_values('IMM', ascending = True)
df2

    Nombre          Raza         IMM
3   Cooper     Schnauzer   70.803832
0    Bella      Labrador   76.530612
2     Lucy     Chow Chow  113.421550
4   Bernie  San Bernardo  124.810255
1  Charlie        Poodle  129.799892

In [175]:
df2 = df2.sort_values('IMM', ascending = False)
df2

    Nombre          Raza         IMM
1  Charlie        Poodle  129.799892
4   Bernie  San Bernardo  124.810255
2     Lucy     Chow Chow  113.421550
0    Bella      Labrador   76.530612
3   Cooper     Schnauzer   70.803832