## Agregación de DF

In [13]:
import numpy as np
import pandas as pd

In [14]:
arreglo = np.array([['Bella', 'Labrador', 'Café', 56, 24, '2013-07-01'],
                    ['Charlie', 'Poodle', 'Negro', 43, 24, '2016-09-16'],
                    ['Lucy', 'Chow Chow', 'Café', 46, 24, '2014-08-25'],
                    ['Cooper', 'Schnauzer', 'Gris', 49, 17, '2011-12-11'],
                    ['Bernie', 'San Bernardo', 'Blanco', 77, 74, '2018-02-27'],
                    ['Max', 'Chow Chow', 'Blanco', 45, 28, '2019-03-27'],
                    ['Reed', 'Schnauzer', 'Negro', 45, 15, '2017-09-18']])
arreglo

array([['Bella', 'Labrador', 'Café', '56', '24', '2013-07-01'],
       ['Charlie', 'Poodle', 'Negro', '43', '24', '2016-09-16'],
       ['Lucy', 'Chow Chow', 'Café', '46', '24', '2014-08-25'],
       ['Cooper', 'Schnauzer', 'Gris', '49', '17', '2011-12-11'],
       ['Bernie', 'San Bernardo', 'Blanco', '77', '74', '2018-02-27'],
       ['Max', 'Chow Chow', 'Blanco', '45', '28', '2019-03-27'],
       ['Reed', 'Schnauzer', 'Negro', '45', '15', '2017-09-18']],
      dtype='<U21')

In [18]:
df = pd.DataFrame(data = arreglo, columns = ['Nombre', 'Raza', 'Color', 'Altura_cm', 'Peso_kg', 'Fecha_Nac'])
df['Altura_cm'] = df['Altura_cm'].astype(int)
df['Peso_kg'] = df['Peso_kg'].astype(int)
df

    Nombre          Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
0    Bella      Labrador    Café         56       24  2013-07-01
1  Charlie        Poodle   Negro         43       24  2016-09-16
2     Lucy     Chow Chow    Café         46       24  2014-08-25
3   Cooper     Schnauzer    Gris         49       17  2011-12-11
4   Bernie  San Bernardo  Blanco         77       74  2018-02-27
5      Max     Chow Chow  Blanco         45       28  2019-03-27
6     Reed     Schnauzer   Negro         45       15  2017-09-18

In [20]:
# Cálculo de la media
df['Peso_kg'].mean()

29.428571428571427

In [24]:
# Cálculo de la fecha de nacimiento más antigua
df['Fecha_Nac'].min()

'2011-12-11'

In [26]:
# Función de agregación estadística
def percentil80(columna):
    return columna.quantile(0.80)

df['Altura_cm'].agg(percentil80)

54.60000000000001

In [28]:
# Agrupación estadística en varias columnas
df[['Altura_cm', 'Peso_kg']].agg(percentil80)

Altura_cm    54.6
Peso_kg      27.2
dtype: float64

In [30]:
df['Altura_cm']

0    56
1    43
2    46
3    49
4    77
5    45
6    45
Name: Altura_cm, dtype: int64

#### Funciones de acumulación

In [34]:
df['Altura_cm'].cumsum() # Sumatoria

0     56
1     99
2    145
3    194
4    271
5    316
6    361
Name: Altura_cm, dtype: int64

In [36]:
df['Altura_cm'].cummin() # Encuentra valor mínimo

0    56
1    43
2    43
3    43
4    43
5    43
6    43
Name: Altura_cm, dtype: int64

In [38]:
# Conteo de perros por raza
df['Raza'].value_counts()

Raza
Chow Chow       2
Schnauzer       2
Labrador        1
Poodle          1
San Bernardo    1
Name: count, dtype: int64

In [40]:
# Proporción de perros por raza
df['Raza'].value_counts(normalize = True)

Raza
Chow Chow       0.285714
Schnauzer       0.285714
Labrador        0.142857
Poodle          0.142857
San Bernardo    0.142857
Name: proportion, dtype: float64

In [46]:
# Promedio de peso por color (Resumen por grupo)
print(df[df['Color'] == 'Blanco']['Peso_kg'].mean())
print(df[df['Color'] == 'Café']['Peso_kg'].mean())
print(df[df['Color'] == 'Gris']['Peso_kg'].mean())
print(df[df['Color'] == 'Negro']['Peso_kg'].mean())

51.0
24.0
17.0
19.5

In [48]:
# Promedio de peso por color (Resumen por grupo) MEJOR OPCIÓN
df.groupby('Color')['Peso_kg'].mean()

Color
Blanco    51.0
Café      24.0
Gris      17.0
Negro     19.5
Name: Peso_kg, dtype: float64

In [54]:
# Agrupación por color en base a diversas estadísticas
df.groupby('Color')['Peso_kg'].agg([min, max, sum])

/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/2042912474.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('Color')['Peso_kg'].agg([min, max, sum])
/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/2042912474.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('Color')['Peso_kg'].agg([min, max, sum])
/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/2042912474.py:2: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.groupby('Color')['Peso_kg'].agg([min, max, sum])

        min  max  sum
Color
Blanco   28   74  102
Café     24   24   48
Gris     17   17   17
Negro    15   24   39

In [56]:
# Agrupación por color en base a diversas estadísticas ¿¿VERSIÓN NUEVA PYTHON??
df.groupby('Color')['Peso_kg'].agg(['min', 'max', 'sum'])

        min  max  sum
Color
Blanco   28   74  102
Café     24   24   48
Gris     17   17   17
Negro    15   24   39

In [58]:
# Agrupación por color y raza en base a la media del peso
df.groupby(['Color', 'Raza'])['Peso_kg'].mean()

Color   Raza
Blanco  Chow Chow       28.0
        San Bernardo    74.0
Café    Chow Chow       24.0
        Labrador        24.0
Gris    Schnauzer       17.0
Negro   Poodle          24.0
        Schnauzer       15.0
Name: Peso_kg, dtype: float64

In [60]:
# Uso de Pivot Tables
df.pivot_table(values = 'Peso_kg', index = 'Color', aggfunc = [np.mean, np.median])

/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/3652127420.py:2: FutureWarning: The provided callable <function mean at 0x107e9c720> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', aggfunc = [np.mean, np.median])
/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/3652127420.py:2: FutureWarning: The provided callable <function median at 0x107fb7420> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', aggfunc = [np.mean, np.median])

          mean  median
       Peso_kg Peso_kg
Color
Blanco    51.0    51.0
Café      24.0    24.0
Gris      17.0    17.0
Negro     19.5    19.5

In [64]:
# Uso de Pivot Tables ¿¿NUEVA VERSIÓN??
df.pivot_table(values = 'Peso_kg', index = 'Color', aggfunc = ['mean', 'median'])

          mean  median
       Peso_kg Peso_kg
Color
Blanco    51.0    51.0
Café      24.0    24.0
Gris      17.0    17.0
Negro     19.5    19.5

In [66]:
# Obtención de promedios para dos variables
df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza') # Media se toma por omisión

Raza    Chow Chow  Labrador  Poodle  San Bernardo  Schnauzer
Color
Blanco       28.0       NaN     NaN          74.0        NaN
Café         24.0      24.0     NaN           NaN        NaN
Gris          NaN       NaN     NaN           NaN       17.0
Negro         NaN       NaN    24.0           NaN       15.0

In [68]:
# Obtención de promedios para dos variables MEJORA NO. 1
df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0) # Media se toma por omisión

Raza    Chow Chow  Labrador  Poodle  San Bernardo  Schnauzer
Color
Blanco       28.0       0.0     0.0          74.0        0.0
Café         24.0      24.0     0.0           0.0        0.0
Gris          0.0       0.0     0.0           0.0       17.0
Negro         0.0       0.0    24.0           0.0       15.0

In [70]:
# Obtención de promedios para dos variables MEJORA NO. 2
df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.mean)

/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/942142871.py:2: FutureWarning: The provided callable <function mean at 0x107e9c720> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.mean) # Media se toma por omisión
/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/942142871.py:2: FutureWarning: The provided callable <function mean at 0x107e9c720> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.mean) # Media se toma por omisión
/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/942142871.py:2: FutureWarning: The provided callable <function mean at 0x107e9c720> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.mean) # Media se toma por omisión

Raza    Chow Chow  Labrador  Poodle  San Bernardo  Schnauzer        All
Color
Blanco       28.0       0.0     0.0          74.0        0.0  51.000000
Café         24.0      24.0     0.0           0.0        0.0  24.000000
Gris          0.0       0.0     0.0           0.0       17.0  17.000000
Negro         0.0       0.0    24.0           0.0       15.0  19.500000
All          26.0      24.0    24.0          74.0       16.0  29.428571

In [72]:
# Obtención de promedios para dos variables MEJORA NO. 2 ¿¿NUEVA VERSIÓN??
df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = 'mean')

Raza    Chow Chow  Labrador  Poodle  San Bernardo  Schnauzer        All
Color
Blanco       28.0       0.0     0.0          74.0        0.0  51.000000
Café         24.0      24.0     0.0           0.0        0.0  24.000000
Gris          0.0       0.0     0.0           0.0       17.0  17.000000
Negro         0.0       0.0    24.0           0.0       15.0  19.500000
All          26.0      24.0    24.0          74.0       16.0  29.428571

In [74]:
# Obtención de medianas para dos variables
df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.median)

/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/831493138.py:2: FutureWarning: The provided callable <function median at 0x107fb7420> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.median)
/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/831493138.py:2: FutureWarning: The provided callable <function median at 0x107fb7420> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.median)
/var/folders/sq/mft37cs11_v620jvyzqlnqvw0000gn/T/ipykernel_61931/831493138.py:2: FutureWarning: The provided callable <function median at 0x107fb7420> is currently using DataFrameGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = np.median)

Raza    Chow Chow  Labrador  Poodle  San Bernardo  Schnauzer   All
Color
Blanco       28.0       0.0     0.0          74.0        0.0  51.0
Café         24.0      24.0     0.0           0.0        0.0  24.0
Gris          0.0       0.0     0.0           0.0       17.0  17.0
Negro         0.0       0.0    24.0           0.0       15.0  19.5
All          26.0      24.0    24.0          74.0       16.0  24.0

In [76]:
# Obtención de medianas para dos variables ¿¿NUEVA VERSIÓN??
df.pivot_table(values = 'Peso_kg', index = 'Color', columns = 'Raza', fill_value = 0, margins = True, aggfunc = 'median')

Raza    Chow Chow  Labrador  Poodle  San Bernardo  Schnauzer   All
Color
Blanco       28.0       0.0     0.0          74.0        0.0  51.0
Café         24.0      24.0     0.0           0.0        0.0  24.0
Gris          0.0       0.0     0.0           0.0       17.0  17.0
Negro         0.0       0.0    24.0           0.0       15.0  19.5
All          26.0      24.0    24.0          74.0       16.0  24.0