# Extracción e Indexación en DataFrames

In [27]:
import numpy as np
import pandas as pd

In [28]:
arreglo = np.array([['Bella', 'Labrador', 'Café', 56, 24, '2013-07-01'],
                    ['Charlie', 'Poodle', 'Negro', 43, 24, '2016-09-16'],
                    ['Lucy', 'Chow Chow', 'Café', 46, 24, '2014-08-25'],
                    ['Cooper', 'Schnauzer', 'Gris', 49, 17, '2011-12-11'],
                    ['Bernie', 'San Bernardo', 'Blanco', 77, 74, '2018-02-27'],
                    ['Max', 'Chow Chow', 'Blanco', 45, 28, '2019-03-27'],
                    ['Reed', 'Schnauzer', 'Negro', 45, 15, '2017-09-18']])
arreglo

array([['Bella', 'Labrador', 'Café', '56', '24', '2013-07-01'],
       ['Charlie', 'Poodle', 'Negro', '43', '24', '2016-09-16'],
       ['Lucy', 'Chow Chow', 'Café', '46', '24', '2014-08-25'],
       ['Cooper', 'Schnauzer', 'Gris', '49', '17', '2011-12-11'],
       ['Bernie', 'San Bernardo', 'Blanco', '77', '74', '2018-02-27'],
       ['Max', 'Chow Chow', 'Blanco', '45', '28', '2019-03-27'],
       ['Reed', 'Schnauzer', 'Negro', '45', '15', '2017-09-18']],
      dtype='<U21')

In [29]:
df = pd.DataFrame(data = arreglo, columns = ['Nombre', 'Raza', 'Color', 'Altura_cm', 'Peso_kg', 'Fecha_Nac'])
df['Altura_cm'] = df['Altura_cm'].astype(int)
df['Peso_kg'] = df['Peso_kg'].astype(int)
df

    Nombre          Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
0    Bella      Labrador    Café         56       24  2013-07-01
1  Charlie        Poodle   Negro         43       24  2016-09-16
2     Lucy     Chow Chow    Café         46       24  2014-08-25
3   Cooper     Schnauzer    Gris         49       17  2011-12-11
4   Bernie  San Bernardo  Blanco         77       74  2018-02-27
5      Max     Chow Chow  Blanco         45       28  2019-03-27
6     Reed     Schnauzer   Negro         45       15  2017-09-18

In [30]:
# Información sobre columnas del DF
df.columns

Index(['Nombre', 'Raza', 'Color', 'Altura_cm', 'Peso_kg', 'Fecha_Nac'], dtype='object')

In [31]:
# Información sobre filas del DF
df.index

RangeIndex(start=0, stop=7, step=1)

In [32]:
# Establecer una columna como índices (títulos de filas)
df_ind = df.set_index('Nombre')
df_ind

                 Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
Nombre
Bella        Labrador    Café         56       24  2013-07-01
Charlie        Poodle   Negro         43       24  2016-09-16
Lucy        Chow Chow    Café         46       24  2014-08-25
Cooper      Schnauzer    Gris         49       17  2011-12-11
Bernie   San Bernardo  Blanco         77       74  2018-02-27
Max         Chow Chow  Blanco         45       28  2019-03-27
Reed        Schnauzer   Negro         45       15  2017-09-18

In [33]:
# Deshacer asignación de índices
df_ind = df_ind.reset_index()
df_ind

    Nombre          Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
0    Bella      Labrador    Café         56       24  2013-07-01
1  Charlie        Poodle   Negro         43       24  2016-09-16
2     Lucy     Chow Chow    Café         46       24  2014-08-25
3   Cooper     Schnauzer    Gris         49       17  2011-12-11
4   Bernie  San Bernardo  Blanco         77       74  2018-02-27
5      Max     Chow Chow  Blanco         45       28  2019-03-27
6     Reed     Schnauzer   Negro         45       15  2017-09-18

In [42]:
df_ind = df.set_index('Nombre')
# Remover índices y columna con información de índices
df_ind = df_ind.reset_index(drop = True)
df_ind

           Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
0      Labrador    Café         56       24  2013-07-01
1        Poodle   Negro         43       24  2016-09-16
2     Chow Chow    Café         46       24  2014-08-25
3     Schnauzer    Gris         49       17  2011-12-11
4  San Bernardo  Blanco         77       74  2018-02-27
5     Chow Chow  Blanco         45       28  2019-03-27
6     Schnauzer   Negro         45       15  2017-09-18

### Ventajas de usar índices

In [45]:
# Opción 1: Búsqueda de nombres en base original
df[df['Nombre'].isin(['Bernie', 'Max'])]

   Nombre          Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
4  Bernie  San Bernardo  Blanco         77       74  2018-02-27
5     Max     Chow Chow  Blanco         45       28  2019-03-27

In [49]:
df_ind = df.set_index('Nombre')
# Opción 2: Búsqueda de nombres en base con índices de nombres
df_ind.loc[['Bernie', 'Max']]

                Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
Nombre
Bernie  San Bernardo  Blanco         77       74  2018-02-27
Max        Chow Chow  Blanco         45       28  2019-03-27

In [53]:
# Generación de índices múltiples (Índices Jerárquicos)
df_ind2 = df.set_index(['Raza', 'Color'])
df_ind2

                      Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza         Color
Labrador     Café      Bella         56       24  2013-07-01
Poodle       Negro   Charlie         43       24  2016-09-16
Chow Chow    Café       Lucy         46       24  2014-08-25
Schnauzer    Gris     Cooper         49       17  2011-12-11
San Bernardo Blanco   Bernie         77       74  2018-02-27
Chow Chow    Blanco      Max         45       28  2019-03-27
Schnauzer    Negro      Reed         45       15  2017-09-18

In [55]:
# Consulta sobre una característica
df_ind2.loc[['Schnauzer', 'Poodle']]

                  Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza      Color
Schnauzer Gris    Cooper         49       17  2011-12-11
          Negro     Reed         45       15  2017-09-18
Poodle    Negro  Charlie         43       24  2016-09-16

In [57]:
# Consulta sobre dos características (usando tuplas)
df_ind2.loc[[('Schnauzer', 'Gris'), ('Poodle', 'Negro')]]

                  Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza      Color
Schnauzer Gris    Cooper         49       17  2011-12-11
Poodle    Negro  Charlie         43       24  2016-09-16

In [59]:
# Ordenamiento por primer índice de referencia
df_ind2.sort_index()

                      Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza         Color
Chow Chow    Blanco      Max         45       28  2019-03-27
             Café       Lucy         46       24  2014-08-25
Labrador     Café      Bella         56       24  2013-07-01
Poodle       Negro   Charlie         43       24  2016-09-16
San Bernardo Blanco   Bernie         77       74  2018-02-27
Schnauzer    Gris     Cooper         49       17  2011-12-11
             Negro      Reed         45       15  2017-09-18

In [61]:
# Ordenamiento por más de un índice
df_ind2.sort_index(level = ['Color', 'Raza'], ascending = True)

                      Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza         Color
Chow Chow    Blanco      Max         45       28  2019-03-27
San Bernardo Blanco   Bernie         77       74  2018-02-27
Chow Chow    Café       Lucy         46       24  2014-08-25
Labrador     Café      Bella         56       24  2013-07-01
Schnauzer    Gris     Cooper         49       17  2011-12-11
Poodle       Negro   Charlie         43       24  2016-09-16
Schnauzer    Negro      Reed         45       15  2017-09-18

In [67]:
# Ordenamiento por más de un índice
df_ind2.sort_index(level = ['Color', 'Raza'], ascending = [True, False]) # False hace que el segundo criterio de sort sea descendente (Raza)

                      Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza         Color
San Bernardo Blanco   Bernie         77       74  2018-02-27
Chow Chow    Blanco      Max         45       28  2019-03-27
Labrador     Café      Bella         56       24  2013-07-01
Chow Chow    Café       Lucy         46       24  2014-08-25
Schnauzer    Gris     Cooper         49       17  2011-12-11
             Negro      Reed         45       15  2017-09-18
Poodle       Negro   Charlie         43       24  2016-09-16

# Slicing

In [71]:
# Extracción de los primeros 3 registros
df[0:3]

    Nombre       Raza  Color  Altura_cm  Peso_kg   Fecha_Nac
0    Bella   Labrador   Café         56       24  2013-07-01
1  Charlie     Poodle  Negro         43       24  2016-09-16
2     Lucy  Chow Chow   Café         46       24  2014-08-25

In [73]:
# Extracción de los primeros 3 registros
df[:3]

    Nombre       Raza  Color  Altura_cm  Peso_kg   Fecha_Nac
0    Bella   Labrador   Café         56       24  2013-07-01
1  Charlie     Poodle  Negro         43       24  2016-09-16
2     Lucy  Chow Chow   Café         46       24  2014-08-25

In [75]:
# Extracción de registros del índice 2 al 4
df[2:5]

   Nombre          Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
2    Lucy     Chow Chow    Café         46       24  2014-08-25
3  Cooper     Schnauzer    Gris         49       17  2011-12-11
4  Bernie  San Bernardo  Blanco         77       74  2018-02-27

In [77]:
# Manera alternativa de extraer todo el DF
df[:]

    Nombre          Raza   Color  Altura_cm  Peso_kg   Fecha_Nac
0    Bella      Labrador    Café         56       24  2013-07-01
1  Charlie        Poodle   Negro         43       24  2016-09-16
2     Lucy     Chow Chow    Café         46       24  2014-08-25
3   Cooper     Schnauzer    Gris         49       17  2011-12-11
4   Bernie  San Bernardo  Blanco         77       74  2018-02-27
5      Max     Chow Chow  Blanco         45       28  2019-03-27
6     Reed     Schnauzer   Negro         45       15  2017-09-18

In [91]:
# Extracción de DF con índices jerárquicos
# 1
df_ind2 = df.set_index(['Raza', 'Color'])
df_ind2

                      Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza         Color
Labrador     Café      Bella         56       24  2013-07-01
Poodle       Negro   Charlie         43       24  2016-09-16
Chow Chow    Café       Lucy         46       24  2014-08-25
Schnauzer    Gris     Cooper         49       17  2011-12-11
San Bernardo Blanco   Bernie         77       74  2018-02-27
Chow Chow    Blanco      Max         45       28  2019-03-27
Schnauzer    Negro      Reed         45       15  2017-09-18

In [93]:
# 2
df_ind2 = df_ind2.sort_index(level = 'Raza', ascending = True)
df_ind2

                      Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza         Color
Chow Chow    Blanco      Max         45       28  2019-03-27
             Café       Lucy         46       24  2014-08-25
Labrador     Café      Bella         56       24  2013-07-01
Poodle       Negro   Charlie         43       24  2016-09-16
San Bernardo Blanco   Bernie         77       74  2018-02-27
Schnauzer    Gris     Cooper         49       17  2011-12-11
             Negro      Reed         45       15  2017-09-18

In [95]:
# 3
df_ind2.loc['Chow Chow':'Labrador']

                 Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza      Color
Chow Chow Blanco    Max         45       28  2019-03-27
          Café     Lucy         46       24  2014-08-25
Labrador  Café    Bella         56       24  2013-07-01

In [101]:
# Para cortar partes de un DF con índices multiples usamos tuplas
df_ind2.loc[('Chow Chow', 'Café'):('Schnauzer', 'Gris')]

                      Nombre  Altura_cm  Peso_kg   Fecha_Nac
Raza         Color
Chow Chow    Café       Lucy         46       24  2014-08-25
Labrador     Café      Bella         56       24  2013-07-01
Poodle       Negro   Charlie         43       24  2016-09-16
San Bernardo Blanco   Bernie         77       74  2018-02-27
Schnauzer    Gris     Cooper         49       17  2011-12-11

In [105]:
# Corte de columnas en DF
df_ind3 = df_ind2.loc[:, 'Nombre':'Peso_kg']
df_ind3

                      Nombre  Altura_cm  Peso_kg
Raza         Color
Chow Chow    Blanco      Max         45       28
             Café       Lucy         46       24
Labrador     Café      Bella         56       24
Poodle       Negro   Charlie         43       24
San Bernardo Blanco   Bernie         77       74
Schnauzer    Gris     Cooper         49       17
             Negro      Reed         45       15

In [107]:
# Extracción simultánea de filas y columnas
df_ind4 = df_ind2.loc[('Chow Chow', 'Café'):('Schnauzer', 'Gris'), 'Nombre':'Peso_kg']
df_ind4

                      Nombre  Altura_cm  Peso_kg
Raza         Color
Chow Chow    Café       Lucy         46       24
Labrador     Café      Bella         56       24
Poodle       Negro   Charlie         43       24
San Bernardo Blanco   Bernie         77       74
Schnauzer    Gris     Cooper         49       17

In [129]:
# Extracción simultánea de filas y columnas
# Opción alternativa por número de fila y número de columna
df_ind4.iloc[1:3,1:3]

                Altura_cm  Peso_kg
Raza     Color
Labrador Café          56       24
Poodle   Negro         43       24

# Cortes en una Pivot Table

In [132]:
# Creación de PT
df_altura_por_raza_color = df.pivot_table('Altura_cm', index = 'Raza', columns = 'Color')
df_altura_por_raza_color

Color         Blanco  Café  Gris  Negro
Raza
Chow Chow       45.0  46.0   NaN    NaN
Labrador         NaN  56.0   NaN    NaN
Poodle           NaN   NaN   NaN   43.0
San Bernardo    77.0   NaN   NaN    NaN
Schnauzer        NaN   NaN  49.0   45.0

In [134]:
# Extracción de registros
df_altura_por_raza_color.loc['Labrador':'San Bernardo']

Color         Blanco  Café  Gris  Negro
Raza
Labrador         NaN  56.0   NaN    NaN
Poodle           NaN   NaN   NaN   43.0
San Bernardo    77.0   NaN   NaN    NaN

In [138]:
# Cálculo de promedios para TODAS las filas (por columna)
df_altura_por_raza_color.mean(axis = 'index')

Color
Blanco    61.0
Café      51.0
Gris      49.0
Negro     44.0
dtype: float64

In [140]:
# Cálculo de promedios para TODAS las columna (por filas)
df_altura_por_raza_color.mean(axis = 'columns')

Raza
Chow Chow       45.5
Labrador        56.0
Poodle          43.0
San Bernardo    77.0
Schnauzer       47.0
dtype: float64