# Entregable 1

### Cargar tablas de datos en Pandas

In [ ]:
# Utiliza la función de Pandas para cargar cada tabla de datos desde el archivo csv o xlsx en un DataFrame.
# (DIM_CATEGORY, DIM_PRODUCT, DIM_SEGMENT, DIM_CALENDAR, FACT_SALES).
import pandas as pd
# Cargar archivos CSV
df_category = pd.read_csv('DIM_CATEGORY.csv')
df_sales = pd.read_csv('FACT_SALES.csv')

# Cargar archivos Excel
df_product = pd.read_excel('DIM_PRODUCT.xlsx')
df_segment = pd.read_excel('DIM_SEGMENT.xlsx')
df_calendar = pd.read_excel('DIM_CALENDAR.xlsx')

### Revisar y entender los datos cargados

In [1]:
# Realiza una revisión rápida de las primeras filas de cada DataFrame para entender la estructura de los datos y sus principales características.
# Utiliza métodos como head(), info() y describe() para tener una idea general del contenido de cada tabla.

# DIM_CATEGORY
print("=== DIM_CATEGORY ===")
df_category.head()
df_category.info()
df_category.describe()

=== DIM_CATEGORY ===

NameError: name 'df_category' is not defined

In [ ]:
# FACT_SALES
print("=== FACT_SALES ===")
df_sales.head()
df_sales.info()
df_sales.describe()

=== FACT_SALES ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122002 entries, 0 to 122001
Data columns (total 6 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   WEEK                         122002 non-null  object
 1   ITEM_CODE                    122002 non-null  object
 2   TOTAL_UNIT_SALES             122002 non-null  float64
 3   TOTAL_VALUE_SALES            122002 non-null  float64
 4   TOTAL_UNIT_AVG_WEEKLY_SALES  122002 non-null  float64
 5   REGION                       122002 non-null  object
dtypes: float64(3), object(3)
memory usage: 5.6+ MB

       TOTAL_UNIT_SALES  TOTAL_VALUE_SALES  TOTAL_UNIT_AVG_WEEKLY_SALES
count     122002.000000      122002.000000                122002.000000
mean           3.211097          90.513761                    10.099904
std           14.496009         350.236505                    22.650142
min            0.000000           0.001000                     0.042000
25%            0.063000           2.662000                     2.316000
50%            0.367000          16.812000                     3.993500
75%            1.520000          62.961500                     8.898000
max          504.681000       12236.759000                   794.000000

In [ ]:
# DIM_PRODUCT
print("=== DIM_PRODUCT ===")
df_product.head()
df_product.info()
df_product.describe()

=== DIM_PRODUCT ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MANUFACTURER      505 non-null    object
 1   BRAND             505 non-null    object
 2   ITEM              503 non-null    object
 3   ITEM_DESCRIPTION  505 non-null    object
 4   CATEGORY          505 non-null    int64
 5   FORMAT            505 non-null    object
 6   ATTR1             499 non-null    object
 7   ATTR2             505 non-null    object
 8   ATTR3             499 non-null    object
dtypes: int64(1), object(8)
memory usage: 35.6+ KB

       CATEGORY
count     505.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

In [ ]:
# DIM_SEGMENT
print("=== DIM_SEGMENT ===")
df_segment.head()
df_segment.info()
df_segment.describe()

=== DIM_SEGMENT ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CATEGORY  53 non-null     int64
 1   ATTR1     53 non-null     object
 2   ATTR2     53 non-null     object
 3   ATTR3     52 non-null     object
 4   FORMAT    53 non-null     object
 5   SEGMENT   53 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.6+ KB

       CATEGORY
count      53.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0

In [ ]:
# DIM_CALENDAR
print("=== DIM_CALENDAR ===")
df_calendar.head()
df_calendar.info()
df_calendar.describe()

=== DIM_CALENDAR ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WEEK         156 non-null    object
 1   YEAR         156 non-null    int64
 2   MONTH        156 non-null    int64
 3   WEEK_NUMBER  156 non-null    int64
 4   DATE         156 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 6.2+ KB

              YEAR       MONTH  WEEK_NUMBER                 DATE
count   156.000000  156.000000   156.000000                  156
mean   2022.000000    6.487179    26.500000  2022-07-06 20:00:00
min    2021.000000    1.000000     1.000000  2021-01-10 00:00:00
25%    2021.000000    3.750000    13.750000  2021-10-08 06:00:00
50%    2022.000000    6.500000    26.500000  2022-07-06 12:00:00
75%    2023.000000    9.250000    39.250000  2023-04-04 18:00:00
max    2023.000000   12.000000    52.000000  2024-01-01 00:00:00
std       0.819126    3.459419    15.056667                  NaN

### Realizar la limpieza de datos

In [ ]:
# Corrige posibles inconsistencias en los datos, como errores tipográficos o formatos incorrectos.
# Identifica y maneja valores nulos en cada DataFrame (si es que los hay).
# Identifica si hay duplicados de los DataFrames y en caso de que los haya, eliminalos.

# DIM_CATEGORY
df_category['CATEGORY'] = df_category['CATEGORY'].str.strip().str.upper()
df_category = df_category.dropna()
df_category = df_category.drop_duplicates()

# DIM_PRODUCT
df_product['BRAND'] = df_product['BRAND'].str.strip().str.upper()
df_product['ITEM_DESCRIPTION'] = df_product['ITEM_DESCRIPTION'].str.strip().str.upper()
df_product = df_product.dropna()
df_product = df_product.drop_duplicates()

# DIM_SEGMENT
df_segment['SEGMENT'] = df_segment['SEGMENT'].str.strip().str.upper()
df_segment = df_segment.dropna()
df_segment = df_segment.drop_duplicates()

# DIM_CALENDAR
df_calendar['DATE'] = pd.to_datetime(df_calendar['DATE'], errors='coerce')
df_calendar = df_calendar.dropna()
df_calendar = df_calendar.drop_duplicates()

# FACT_SALES
df_sales['TOTAL_UNIT_SALES'] = pd.to_numeric(df_sales['TOTAL_UNIT_SALES'], errors='coerce')
df_sales['TOTAL_VALUE_SALES'] = pd.to_numeric(df_sales['TOTAL_VALUE_SALES'], errors='coerce')
df_sales = df_sales.dropna()
df_sales = df_sales.drop_duplicates()

### Unir los DataFrames relevantes

In [ ]:
# Unión de FACT_SALES con DIM_PRODUCT
df_ventas_productos = pd.merge(df_sales, df_product, how='left', left_on='ITEM_CODE', right_on='ITEM')
df_ventas_productos

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058792778BP1,VANISHOXIACTIONROSABOTE900GR+MMCRYSTALWHITEDOY...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058757630,VANISH PODER O2 PRE-LAVADOR BOT.ATOM. 650 ML N...,1,LIQUIDO,PRELAVADOR,FABRIC TREATMENT,ROSA
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058753441,VANISH PODER O2 DOYPACK 120 GR 7501058753441,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7702626204208BP1,VANISH PODER 02 INTELIGENCE SIN CLORO SOBRE 30...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058784346,VANISH PODER 02 INTELLIGENCE POLVO BOT 900 GR ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA

In [ ]:
# Convertir ambas columnas CATEGORY a tipo texto para que coincidan
df_ventas_productos['CATEGORY'] = df_ventas_productos['CATEGORY'].astype(str)
df_category['CATEGORY'] = df_category['CATEGORY'].astype(str)
# Unión con DIM_CATEGORY
df_ventas_productos_categorias = pd.merge(df_ventas_productos, df_category, how='left', on='CATEGORY')
df_ventas_productos_categorias

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058792778BP1,VANISHOXIACTIONROSABOTE900GR+MMCRYSTALWHITEDOY...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058757630,VANISH PODER O2 PRE-LAVADOR BOT.ATOM. 650 ML N...,1,LIQUIDO,PRELAVADOR,FABRIC TREATMENT,ROSA,NaN
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058753441,VANISH PODER O2 DOYPACK 120 GR 7501058753441,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7702626204208BP1,VANISH PODER 02 INTELIGENCE SIN CLORO SOBRE 30...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058784346,VANISH PODER 02 INTELLIGENCE POLVO BOT 900 GR ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN

In [ ]:
# Unión con DIM_SEGMENT
# Convertir columnas a string en ambos DataFrames para asegurar compatibilidad
columnas_union = ['CATEGORY', 'FORMAT', 'ATTR1', 'ATTR2', 'ATTR3']
for col in columnas_union:
    df_ventas_productos_categorias[col] = df_ventas_productos_categorias[col].astype(str)
    df_segment[col] = df_segment[col].astype(str)

# Hacer la unión final
df_final = pd.merge(df_ventas_productos_categorias, df_segment, how='left', on=columnas_union)
df_final

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,SEGMENT
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058792778BP1,VANISHOXIACTIONROSABOTE900GR+MMCRYSTALWHITEDOY...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058757630,VANISH PODER O2 PRE-LAVADOR BOT.ATOM. 650 ML N...,1,LIQUIDO,PRELAVADOR,FABRIC TREATMENT,ROSA,NaN,PRETREAT
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058753441,VANISH PODER O2 DOYPACK 120 GR 7501058753441,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7702626204208BP1,VANISH PODER 02 INTELIGENCE SIN CLORO SOBRE 30...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058784346,VANISH PODER 02 INTELLIGENCE POLVO BOT 900 GR ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER

### Aplicar transformaciones necesarias

In [ ]:
# Estandariza los formatos de las columnas, como las fechas o categorías, para asegurar la consistencia
# en todo el conjunto de datos.
# Realiza cualquier transformación adicional requerida para preparar los datos para el análisis,
# como la creación de nuevas columnas calculadas o la agrupación de datos.

# Convertir columnas de texto clave a mayúsculas y eliminar espacios
columnas_texto = ['CATEGORY', 'BRAND', 'FORMAT', 'ATTR1', 'ATTR2', 'ATTR3', 'SEGMENT']
for col in columnas_texto:
    if col in df_final.columns:
        df_final[col] = df_final[col].str.strip().str.upper()

# Convertir columnas numéricas a tipo numérico (por si hay errores de formato)
df_final['TOTAL_UNIT_SALES'] = pd.to_numeric(df_final['TOTAL_UNIT_SALES'], errors='coerce')
df_final['TOTAL_VALUE_SALES'] = pd.to_numeric(df_final['TOTAL_VALUE_SALES'], errors='coerce')

In [ ]:
# Crear columna de precio promedio por unidad
df_final['UNIT_PRICE'] = df_final['TOTAL_VALUE_SALES'] / df_final['TOTAL_UNIT_SALES']
df_final

,WEEK,ITEM_CODE,TOTAL_UNIT_SALES,TOTAL_VALUE_SALES,TOTAL_UNIT_AVG_WEEKLY_SALES,REGION,MANUFACTURER,BRAND,ITEM,ITEM_DESCRIPTION,CATEGORY,FORMAT,ATTR1,ATTR2,ATTR3,ID_CATEGORY,SEGMENT,UNIT_PRICE
0,34-22,7501058792808BP2,0.006,0.139,1.000,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058792808BP2,VANISHOXIACTIONROSADOYPACK120GR+MMCRYSTALWHITE...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,23.166667
1,34-22,7501058715883,0.487,116.519,2.916,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058715883,VANISH OXI ACTION GOLD QUITAMANCHAS BOLSA 1.8K...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,239.258727
2,34-22,7702626213774,1.391,68.453,5.171,TOTAL AUTOS AREA 5,RECKITT,VANISH,7702626213774,VANISH OXI ACTION ROSA QUITAMANCHAS DOYPACK 24...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,49.211359
3,34-22,7501058716422,0.022,1.481,1.833,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058716422,VANISH OXI ACTION GOLD QUITAMANCHA AHORRO DEL ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,67.318182
4,34-22,7501058784353,2.037,182.839,5.375,TOTAL AUTOS AREA 5,RECKITT,VANISH,7501058784353,VANISH INTELLIGENCE POLVO BOTE 450 GR NAL 7501...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,89.758959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121997,26-23,7501058792778BP1,1.192,150.829,4.000,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058792778BP1,VANISHOXIACTIONROSABOTE900GR+MMCRYSTALWHITEDOY...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,126.534396
121998,26-23,7501058757630,1.947,235.416,2.797,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058757630,VANISH PODER O2 PRE-LAVADOR BOT.ATOM. 650 ML N...,1,LIQUIDO,PRELAVADOR,FABRIC TREATMENT,ROSA,NaN,PRETREAT,120.912173
121999,26-23,7501058753441,18.013,429.289,9.102,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058753441,VANISH PODER O2 DOYPACK 120 GR 7501058753441,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,23.832177
122000,26-23,7702626204208BP1,21.152,210.276,22.172,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7702626204208BP1,VANISH PODER 02 INTELIGENCE SIN CLORO SOBRE 30...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,9.941188
122001,26-23,7501058784346,1.468,301.973,2.068,TOTAL AUTOS SCANNING MEXICO,RECKITT,VANISH,7501058784346,VANISH PODER 02 INTELLIGENCE POLVO BOT 900 GR ...,1,POLVO,SAFE BLEACH,FABRIC TREATMENT,ROSA,NaN,POWDER,205.703678

In [ ]:

# Agrupar ventas por categoría
ventas_por_categoria = df_final.groupby('CATEGORY')[['TOTAL_UNIT_SALES', 'TOTAL_VALUE_SALES']].sum().reset_index()
ventas_por_categoria

  CATEGORY  TOTAL_UNIT_SALES  TOTAL_VALUE_SALES
0        1        391760.228       1.104286e+07

In [ ]:
# Creo que sería buena idea también incluir el df_calendar
# Asegurar que 'WEEK' sea del mismo tipo en ambos DataFrames
df_final['WEEK'] = df_final['WEEK'].astype(int)
df_calendar['WEEK'] = df_calendar['WEEK'].astype(int)

# Unir por la columna 'WEEK'
df_final = pd.merge(df_final, df_calendar, how='left', on='WEEK')

### Guardar el conjunto de datos consolidado

In [ ]:
# Guarda el DataFrame consolidado en un nuevo archivo CSV o Excel para su uso posterior en el análisis.
df_final.to_excel('DATOS_CONSOLIDADOS.xlsx', index=False)